--DROPS
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS user_balance;
DROP TABLE IF EXISTS records;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS operations;

--CREATES
CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(120) NOT NULL,
  status BOOLEAN DEFAULT TRUE
);
CREATE TABLE roles (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(20) NOT NULL
);
CREATE TABLE user_roles (
  user_id INT NOT NULL,
  role_id INT NOT NULL
);
CREATE TABLE operations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  cost NUMERIC(20, 2) NOT NULL
);
CREATE TABLE records (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  operation_id INT NOT NULL,
  user_id INT NOT NULL,
  amount NUMERIC(20, 2),
  user_balance NUMERIC(20, 2),
  operation_response VARCHAR(50),
  date_operation DATE NOT NULL,
  deleted BOOLEAN DEFAULT FALSE
);
CREATE TABLE user_balance (
  user_id INT PRIMARY KEY,
  balance NUMERIC(20, 2)
);