--CREATE TABLES USER LOGIN SECURITY
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS user_roles;
CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(120) NOT NULL,
  status BOOLEAN DEFAULT TRUE
);
CREATE TABLE roles (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(20) NOT NULL
);
CREATE TABLE user_roles (
  user_id INT NOT NULL,
  role_id INT NOT NULL
);
--CREATE TABLES MATH OPERATIONS
DROP TABLE IF EXISTS operations;
DROP TABLE IF EXISTS records;
CREATE TABLE operations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  type VARCHAR(50) NOT NULL,
  cost NUMERIC NOT NULL
);
CREATE TABLE records (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  operation_id NUMERIC NOT NULL,
  user_id NUMERIC NOT NULL,
  amount NUMERIC,
  user_balance NUMERIC,
  operation_response VARCHAR(50),
  date DATE NOT NULL
);
--CREATE TABLE USER BALANCE
DROP TABLE IF EXISTS user_balance;
CREATE TABLE user_balance (
  user_id NUMERIC PRIMARY KEY,
  balance NUMERIC
);